{application,phoscon_provider,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{phoscon_provider_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[phoscon_provider,phoscon_provider_app,
                        phoscon_provider_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
